name: Build and Deploy StockPriceSheetPrintService
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
    concurrency:
      group: build-stock-price-sheet-print-service-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
        env:
          DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet
      - name: Restore local tools
        run: dotnet tool restore
      - name: Begin analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"Hjaltechristensen_StockPriceSheetPrintService" /o:"hjaltechristensen" /d:sonar.token="$SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io"
      - name: Build and test
        run: dotnet test --project ArchUnitTest/ArchUnitTest.csproj --configuration Release
      - name: End analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: self-hosted
    permissions: {}
    concurrency:
      group: deploy-stock-price-sheet-print-service
      cancel-in-progress: true
    steps:
      - name: Deploy service
        run: |
          echo "Deploying..."
          cd /home/hjalte/deploy/update
          ./update.sh "${{ github.event.repository.name }}"
